name: Clojure CI

on: [push, pull_request]

env:
  JAVA_VERSION: 11
  JAVA_DISTRIBUTION: "temurin"
  LEIN_VERSION: 2.11.2

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Install Leiningen
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          lein: ${{ env.LEIN_VERSION }}
      - name: Cache clojure dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ hashFiles('project.clj') }}
          restore-keys: cljdeps-
      - name: Run tests
        run: lein test
